/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseWrapper: typeof import('./src/components/Base/BaseWrapper.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test1: typeof import('./src/components/Test1/index.vue')['default']
    Test2: typeof import('./src/components/Test2/index.vue')['default']
  }
}
